# Generated by Django 3.2.6 on 2021-08-07 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='camera_id',
            new_name='camera',
        ),
    ]
