# Generated by Django 3.2.6 on 2021-08-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_rename_camera_id_picture_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='state',
            field=models.CharField(choices=[(0, 'ONLINE'), (1, 'OFFLINE'), (2, 'ERROR'), (3, 'DEACTIVATED'), (4, 'MISSING_SDCARD')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='camera',
            name='interval',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip4',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.BinaryField(blank=True),
        ),
    ]
