# Generated by Django 3.2.6 on 2021-08-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_auto_20210807_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='filename',
            field=models.CharField(default='h', max_length=64),
            preserve_default=False,
        ),
    ]
